Suppress suggestion to use "field backed properties"
Bumping C# language version to 14 surfaces a bunch of inspections like

```
Error: /home/runner/work/osu-framework/osu-framework/osu.Framework/Allocation/TimedExpiryCache.cs(97,13): error IDE0032: Use auto property (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0032) [/home/runner/work/osu-framework/osu-framework/osu.Framework/osu.Framework.csproj]
```

The change that the compiler here attempts to enforce is:

```diff
diff --git a/osu.Framework/Allocation/TimedExpiryCache.cs b/osu.Framework/Allocation/TimedExpiryCache.cs
index f851524ecf..d25ce17662 100644
--- a/osu.Framework/Allocation/TimedExpiryCache.cs
+++ b/osu.Framework/Allocation/TimedExpiryCache.cs
@@ -94,20 +94,18 @@ private class TimedObject<T>
         {
             public DateTimeOffset LastAccessTime;

-            private readonly T value;
-
             public T Value
             {
                 get
                 {
                     updateAccessTime();
-                    return value;
+                    return field;
                 }
             }

             public TimedObject(T value)
             {
-                this.value = value;
+                Value = value;
                 updateAccessTime();
             }

```

What this is, is a new C# 14 language feature called ["field backed
properties"](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/field).
The gist of it appears to be that you apparently are no longer required
to declare a backing field yourself, and instead you can use a new
`field` keyword to refer to the automatically-generated backing field.
Assignments to the backing field - if any - are replaced with
assignments to the property which... has no getter.

To me this is quite abhorrent. Unfortunately there is no `.editorconfig`
switch targeted at this specific new dingle, or at least I can't find
one. You have to completely shut down the auto-property enforcement on
that level. ReSharper will still enforce that, but the C# compiler
itself will not.

Chuck another C# language release in the "half of new features is neat,
half is horrible abominations" bin I guess.